# Generated by Django 4.2 on 2025-06-16 10:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AddField(
            model_name='goal',
            name='custom_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='goal',
            name='default_title',
            field=models.CharField(blank=True, choices=[('Emergency Fund', 'Emergency Fund'), ('Vacation', 'Vacation'), ('New Car', 'New Car'), ('Education', 'Education'), ('Home Purchase', 'Home Purchase')], max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=timezone.now),
        ),
    ]
