# Generated by Django 4.2 on 2025-06-16 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_created_at_remove_goal_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
